from docker.io/library/rust:1.96-alpine@sha256:a41f7740f8b45d45795624eec13a8b42263cc700f19f7e4e86e04d3dda08a479 as builder

    run apk add --no-cache \
        protobuf

    workdir /github.com/lukasdietrich/dhcp-template

    copy crates/ ./crates
    copy Cargo.toml Cargo.lock ./

    run cargo build --release --bin dhcp-template-operator

from docker.io/library/alpine:3@sha256:28bd5fe8b56d1bd048e5babf5b10710ebe0bae67db86916198a6eec434943f8b

    workdir /app

    copy --from=builder /github.com/lukasdietrich/dhcp-template/target/release/dhcp-template-operator ./
    copy LICENSE ./

    label org.opencontainers.image.authors="Lukas Dietrich <lukas@lukasdietrich.com>"
    label org.opencontainers.image.source="https://github.com/lukasdietrich/dhcp-template"

    cmd [ "/app/dhcp-template-operator" ]
